### ISSUE TITLE
Intrebare qotd

### ISSUE THREAD

**Issue by alexef** [rosedu/wouso-content#3]
Cum este referita, de GRUB, a 2-a partitie de pe al 3-lea harddisk ?
(hd1, 2)
(hd2, 1)
(hd2, 3)
[corect](hd3, 2)

Nu incep de la 0? - Branescu Adrian

**Comment by razvand** [comment]
Ba da. Am corectat eu (https://wouso.cs.pub.ro/2012/cpanel/qpool/edit/1085/).

**Comment by alexef** [comment]
I-am dat gold.
